#+TITLE:     Installation
#+AUTHOR:    
#+EMAIL:     alexat3@rpi.edu
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t email:nil author:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:t timestamp:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LaTeX_CLASS_OPTIONS: [12pt,letterpaper,bookmarks=false,colorlinks=true,linkcolor=blue,pdfstartview=FitH]
* Prerequisites
singleplayerdrinkinggames.com has three components: The MySQL database, the PHP server side scripts, and the Dart frontend. In order to deploy this project you will need a web server. Our choice of server-side technology was heavily influenced by the prevalence of LAMP (Linux, Apache, MySQL, and PHP) servers on the web. Most shared web hosts today will provide you with a LAMP server out of the box, but if you would like to roll your own there are many tutorials online including [[http://www.howtoforge.com/ubuntu_debian_lamp_server][this one]].

You will also need a copy of the [[http://www.dartlang.org/tools/sdk/][Dart SDK]] in order to compile the dart code into javascript. The SDK is cross platform so any popular operating system will be able to run it.
* Populate MySQL
Once you have your LAMP server set up, you will need to populate a MySQL database with the necessary tables. First create a new database with any name you want. Next we will need to import a copy of the tables. This copy is named =db.sql=. There are two methods of importing the data: command-line or graphical through phpMyAdmin.
** Command-line Import
- From a machine with the MySQL client installed, connect to your database and pipe the dump in on stdin. An example: =mysql -u myusername -p1234 -h mysql.singleplayerdrinkinggames.com singleplayerdb < db.sql=
** phpMyAdmin Import
1. Log onto phpMyAdmin and select your new database
2. Ensure the database is empty
3. At the top of your page click the =Import= tab
4. Click the =Choose File= button and select =db.sql=
5. Click =Ok=
* Compilation and Deployment
There are two ways we can compile and deploy the code: Automatically through deploy.sh or manually
** Automatic Deployment
1. In the root of the source code you will find a script named =deploy.sh=
2. Edit deploy.sh
   1. Change REMOTEUSER to your ssh username on the server
   2. Change HOST to your server
   3. Change the path in the rsync commands from =~/singleplayerdrinkinggames.com= to your web accessible directory (for ex: =/var/www/=)
3. Ensure dart2js is located in your =$PATH=. You can confirm this by running =which dart2js=
4. Edit =backend/db_functions.php=
   1. Change the MySql host to your MySQL server
   2. Change dbname to the name of your database
   3. Change the two parameters that follow dbname to your database username and password respectively
5. Run deploy.sh
6. Go to your website and confirm the site loads properly
** Manual Deployment
1. Ensure dart2js is located in your =$PATH=. You can confirm this by running =which dart2js=
2. Edit =backend/db_functions.php=
   1. Change the MySql host to your MySQL server
   2. Change dbname to the name of your database
   3. Change the two parameters that follow dbname to your database username and password respectively
3. Enter the folder named =frontend= and run =dart2js -omain.js --minify main.dart=
4. Copy everything inside =backend/web_root/= into the top-level web accessible directory (sometimes =/var/www/=)
5. Copy =backend/db_functions.php= to the directory 1 level above the web accessible directory
6. Copy the =images= folder to the top-level web accessible directory
7. Copy all =main.js=, =index.html= and =styles.less= to the top-level web accessible directory
8. Go to your website and confirm the site loads properly
